include classpath("application.conf")

node-address {
  protocol = http
  host = "elasticmq"
  port = 9324
  context-path = ""
}

rest-stats {
  enabled = true
  bind-hostname = "0.0.0.0"
  bind-port = 9325
}

queues {
  lambda-worker-queue {}
  ecs-worker-queue {}
}
