version: 0.0
Resources:
  - LambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: ${FUNCTION_NAME}
        Alias: ${FUNCTION_ALIAS}
        CurrentVersion: ${CURRENT_VERSION}
        TargetVersion: ${NEW_VERSION}