name: Deploy Lambda with CodeDeploy
description: Deploy a Lambda using Terragrunt + CodeDeploy (publish version, traffic shift, prune)

inputs:
  aws_oidc_role_arn:
    description: AWS OIDC role to assume
    required: true

  infra_version:
    description: Git ref containing Terraform/Terragrunt config
    required: true

  tg_directory:
    description: Terragrunt directory for this lambda
    required: true

  lambda_bucket:
    description: "Bucket containing lambda zips"
    required: true

  lambda_version:
    description: Lambda artifact version (S3 prefix)
    required: true

  lambda_keep:
    description: Number of lambda versions to keep
    required: true
    
runs:
  using: composite
  steps:
    - name: Get Terragrunt outputs
      id: init
      uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.1
      with:
        aws_oidc_role_arn: ${{ inputs.aws_oidc_role_arn }}
        tg_directory: ${{ inputs.tg_directory }}
        tg_action: init

    - name: Extract Terragrunt outputs
      id: vars
      shell: bash
      env:
        TG_OUTPUTS: ${{ steps.init.outputs.tg_outputs }}
      run: |
        echo "lambda_zip_key=$(echo $TG_OUTPUTS | jq -r '.lambda_zip_key.value')" >> $GITHUB_OUTPUT
        echo "lambda_function_name=$(echo $TG_OUTPUTS | jq -r '.lambda_function_name.value')" >> $GITHUB_OUTPUT
        echo "lambda_alias_name=$(echo $TG_OUTPUTS | jq -r '.lambda_alias_name.value')" >> $GITHUB_OUTPUT
        echo "code_deploy_app_name=$(echo $TG_OUTPUTS | jq -r '.code_deploy_app_name.value')" >> $GITHUB_OUTPUT
        echo "code_deploy_group_name=$(echo $TG_OUTPUTS | jq -r '.code_deploy_group_name.value')" >> $GITHUB_OUTPUT

    - name: Get current lambda version
      id: get-version
      uses: chrispsheehan/just-aws-oidc-action@0.1.3
      env:
        FUNCTION_NAME: ${{ steps.vars.outputs.lambda_function_name }}
        ALIAS_NAME: ${{ steps.vars.outputs.lambda_alias_name }}
      with:
        aws_oidc_role_arn: ${{ inputs.aws_oidc_role_arn }}
        just_action: lambda-get-version

    - name: Publish new lambda version
      id: publish
      uses: chrispsheehan/just-aws-oidc-action@0.1.3
      env:
        BUCKET_NAME: ${{ inputs.lambda_bucket }}
        FUNCTION_NAME: ${{ steps.vars.outputs.lambda_function_name }}
        LAMBDA_ZIP_KEY: ${{ steps.vars.outputs.lambda_zip_key }}
      with:
        aws_oidc_role_arn: ${{ inputs.aws_oidc_role_arn }}
        just_action: lambda-create-version

    - name: Upload AppSpec bundle
      uses: chrispsheehan/just-aws-oidc-action@0.1.3
      env:
        BUCKET_NAME: ${{ inputs.lambda_bucket }}
        FUNCTION_NAME: ${{ steps.vars.outputs.lambda_function_name }}
        ALIAS_NAME: ${{ steps.vars.outputs.lambda_alias_name }}
        CURRENT_VERSION: ${{ steps.get-version.outputs.just_outputs }}
        NEW_VERSION: ${{ steps.publish.outputs.just_outputs }}
        APP_SPEC_FILE: ${{ github.workspace }}/appspec.yml
        APP_SPEC_KEY: ${{ github.workspace }}/${{ inputs.tg_directory }}/appspec.zip
      with:
        aws_oidc_role_arn: ${{ inputs.aws_oidc_role_arn }}
        just_action: lambda-upload-bundle

    - name: Run CodeDeploy
      uses: chrispsheehan/just-aws-oidc-action@0.1.3
      env:
        BUCKET_NAME: ${{ inputs.lambda_bucket }}
        CODE_DEPLOY_APP_NAME: ${{ steps.vars.outputs.code_deploy_app_name }}
        CODE_DEPLOY_GROUP_NAME: ${{ steps.vars.outputs.code_deploy_group_name }}
        APP_SPEC_KEY: ${{ github.workspace }}/${{ inputs.tg_directory }}/appspec.zip
      with:
        aws_oidc_role_arn: ${{ inputs.aws_oidc_role_arn }}
        just_action: lambda-deploy

    - name: Prune old lambda versions
      uses: chrispsheehan/just-aws-oidc-action@0.1.3
      env:
        KEEP: ${{ inputs.lambda_keep }}
        FUNCTION_NAME: ${{ steps.vars.outputs.lambda_function_name }}
        ALIAS_NAME: ${{ steps.vars.outputs.lambda_alias_name }}
      with:
        aws_oidc_role_arn: ${{ inputs.aws_oidc_role_arn }}
        just_action: lambda-prune
