name: Deploy Lambda with CodeDeploy
description: Deploy a Lambda using Terragrunt + CodeDeploy (publish version, traffic shift, prune)

inputs:
  aws_oidc_role_arn:
    description: AWS OIDC role to assume
    required: true

  lambda_bucket:
    description: "Bucket containing lambda zips"
    required: true

  lambda_version:
    description: Lambda artifact version (S3 prefix)
    required: true
    
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: Set AppSpec paths
      id: appspec
      shell: bash
      run: |
        lambda_zip_key="${{ inputs.lambda_version }}/${{ steps.vars.outputs.lambda_function_name }}.zip"
        lambda_appspec_key="${{ inputs.lambda_version }}/${{ steps.vars.outputs.lambda_function_name }}-appspec.zip"
        echo "lambda_appspec_key=$(echo $TG_OUTPUTS | jq -r '.lambda_zip_key.value')" >> $GITHUB_OUTPUT
        echo "lambda_appspec_zip=$(echo $TG_OUTPUTS | jq -r '.lambda_function_name.value')" >> $GITHUB_OUTPUT


    - name: Publish new lambda version
      id: publish
      uses: chrispsheehan/just-aws-oidc-action@0.1.3
      env:
        BUCKET_NAME: ${{ inputs.lambda_bucket }}
        FUNCTION_NAME: ${{ steps.vars.outputs.lambda_function_name }}
        LAMBDA_ZIP_KEY: ${{ steps.vars.outputs.lambda_zip_key }}
      with:
        aws_oidc_role_arn: ${{ inputs.aws_oidc_role_arn }}
        just_action: lambda-create-version

