name: Deploy Lambda with CodeDeploy
description: Deploy a Lambda using Terragrunt + CodeDeploy (publish version, traffic shift, prune)

inputs:
  aws_oidc_role_arn:
    description: AWS OIDC role to assume
    required: true

  lambda_bucket:
    description: "Bucket containing lambda zips"
    required: true

  lambda_version:
    description: Lambda artifact version (S3 prefix)
    required: true

  lambda_keep:
    description: Number of lambda versions to keep
    required: true
    
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: Set AppSpec paths
      id: appspec
      shell: bash
      run: |
        lambda_zip_key="${{ inputs.lambda_version }}/${{ steps.vars.outputs.lambda_function_name }}.zip"
        lambda_appspec_key="${{ inputs.lambda_version }}/${{ steps.vars.outputs.lambda_function_name }}-appspec.zip"
        echo "lambda_appspec_key=$(echo $TG_OUTPUTS | jq -r '.lambda_zip_key.value')" >> $GITHUB_OUTPUT
        echo "lambda_appspec_zip=$(echo $TG_OUTPUTS | jq -r '.lambda_function_name.value')" >> $GITHUB_OUTPUT

    - name: Get current lambda version
      id: get-version
      uses: chrispsheehan/just-aws-oidc-action@0.1.3
      env:
        FUNCTION_NAME: ${{ steps.vars.outputs.lambda_function_name }}
        ALIAS_NAME: ${{ steps.vars.outputs.lambda_alias_name }}
      with:
        aws_oidc_role_arn: ${{ inputs.aws_oidc_role_arn }}
        just_action: lambda-get-version

    - name: Publish new lambda version
      id: publish
      uses: chrispsheehan/just-aws-oidc-action@0.1.3
      env:
        BUCKET_NAME: ${{ inputs.lambda_bucket }}
        FUNCTION_NAME: ${{ steps.vars.outputs.lambda_function_name }}
        LAMBDA_ZIP_KEY: ${{ steps.vars.outputs.lambda_zip_key }}
      with:
        aws_oidc_role_arn: ${{ inputs.aws_oidc_role_arn }}
        just_action: lambda-create-version

    - name: Upload AppSpec bundle
      uses: chrispsheehan/just-aws-oidc-action@0.1.3
      env:
        BUCKET_NAME: ${{ inputs.lambda_bucket }}
        FUNCTION_NAME: ${{ steps.vars.outputs.lambda_function_name }}
        ALIAS_NAME: ${{ steps.vars.outputs.lambda_alias_name }}
        CURRENT_VERSION: ${{ steps.get-version.outputs.just_outputs }}
        NEW_VERSION: ${{ steps.publish.outputs.just_outputs }}
        APP_SPEC_FILE: ${{ github.workspace }}/appspec.yml
        APP_SPEC_KEY: ${{ steps.vars.outputs.lambda_appspec_key }}
      with:
        aws_oidc_role_arn: ${{ inputs.aws_oidc_role_arn }}
        just_action: lambda-upload-bundle

    - name: Run CodeDeploy
      uses: chrispsheehan/just-aws-oidc-action@0.1.3
      env:
        FUNCTION_NAME: ${{ steps.vars.outputs.lambda_function_name }}
        BUCKET_NAME: ${{ inputs.lambda_bucket }}
        APP_SPEC_KEY: ${{ steps.vars.outputs.lambda_appspec_key }}
      with:
        aws_oidc_role_arn: ${{ inputs.aws_oidc_role_arn }}
        just_action: lambda-deploy

    - name: Prune old lambda versions
      uses: chrispsheehan/just-aws-oidc-action@0.1.3
      env:
        KEEP: ${{ inputs.lambda_keep }}
        FUNCTION_NAME: ${{ steps.vars.outputs.lambda_function_name }}
        ALIAS_NAME: ${{ steps.vars.outputs.lambda_alias_name }}
      with:
        aws_oidc_role_arn: ${{ inputs.aws_oidc_role_arn }}
        just_action: lambda-prune
