name: Prod Deploy Infra and Code

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  get_build:
    uses: ./.github/workflows/build_get.yml
    with:
      environment: ci
      lambda_version: 0.7.2

  infra:
    needs: 
      - get_build
    uses: ./.github/workflows/infra.yml
    with:
      environment: prod
      infra_version: 0.7.2
      code_bucket: ${{ needs.get_build.outputs.code_bucket }}
      lambda_matrix: ${{ needs.get_build.outputs.lambda_version_files }}

  deploy:
    uses: ./.github/workflows/deploy.yml
    needs: 
      - get_build
      - infra # this is only to ensure infra runs before deploy no dependencies on infra outputs i.e. infra is managed separately
    with:
      environment: prod
      code_bucket: ${{ needs.get_build.outputs.code_bucket }}
      lambda_version: ${{ needs.get_build.outputs.lambda_version }}
      lambda_matrix: ${{ needs.get_build.outputs.lambda_version_files }}
      frontend_version: ${{ needs.get_build.outputs.frontend_version }}
