name: Dev Deploy Full

on:
  workflow_dispatch:
  push:
    branches:
      - ecs

permissions:
  id-token: write
  contents: write

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      lambdas_dirs: ${{ steps.lambdas_dirs.outputs.just_outputs }}
      service_dirs: ${{ steps.service_dirs.outputs.just_outputs }}
      task_dirs: ${{ steps.task_dirs.outputs.just_outputs }}
      ecs_service_dirs: ${{ steps.ecs_service_dirs.outputs.just_outputs }}
    steps:
      - uses: actions/checkout@v6

      - name: Get lambdas Directories
        id: lambdas_dirs
        uses: chrispsheehan/just-aws-oidc-action@0.3.0
        with:
          just_action: lambda-get-directories

      - name: Get Service Directories
        id: service_dirs
        uses: chrispsheehan/just-aws-oidc-action@0.3.0
        with:
          just_action: service-get-directories

      - name: Get Task Directories
        id: task_dirs
        uses: chrispsheehan/just-aws-oidc-action@0.3.0
        with:
          just_action: task-get-directories

      - name: Get ECS Service Directories
        id: ecs_service_dirs
        uses: chrispsheehan/just-aws-oidc-action@0.3.0
        with:
          just_action: ecs-service-get-directories

  code:
    uses: ./.github/workflows/infra_releases.yml
    with:
      environment: dev
      infra_version: ${{ github.sha }}

  infra:
    needs: 
      - setup
      - code
    uses: ./.github/workflows/infra.yml
    with:
      environment: dev
      infra_version: ${{ github.sha }}
      code_bucket: ${{ needs.code.outputs.code_bucket }}
      lambda_matrix: ${{ needs.setup.outputs.lambdas_dirs }}
      bootstrap_image_uri: ${{ needs.code.outputs.bootstrap_image_uri }}
      service_matrix: ${{ needs.setup.outputs.ecs_service_dirs }}

  # build:
  #   uses: ./.github/workflows/build.yml
  #   needs:
  #     - code
  #     - setup
  #   with:
  #     environment: dev
  #     lambda_version: ${{ github.sha }}
  #     frontend_version: ${{ github.sha }}
  #     ecs_version: ${{ github.sha }}
  #     lambda_matrix: ${{ needs.setup.outputs.lambdas_dirs }}
  #     ecs_matrix: ${{ needs.setup.outputs.service_dirs }}

  # get_build:
  #   needs: build
  #   uses: ./.github/workflows/build_get.yml
  #   with:
  #     environment: dev
  #     lambda_version: ${{ github.sha }}
  #     frontend_version: ${{ github.sha }}
  #     ecs_version: ${{ github.sha }}

  # deploy:
  #   uses: ./.github/workflows/deploy.yml
  #   needs:
  #     - setup
  #     - get_build
  #     - infra
  #   with:
  #     environment: dev
  #     lambda_version: ${{ github.sha }}
  #     frontend_version: ${{ github.sha }}
  #     code_bucket: ${{ needs.get_build.outputs.code_bucket }}
  #     lambda_matrix: ${{ needs.setup.outputs.lambdas_dirs }}
      # task_matrix: ${{ needs.setup.outputs.task_dirs }}
      # ecs_service_matrix: ${{ needs.setup.outputs.ecs_service_dirs }}
