name: Prod Deploy Code Only
# This allows us to deploy only code changes to prod found in the version s3 folder (only).

on:
  workflow_dispatch:
    inputs:
      infra_version:
        description: "Release tag to deploy e.g. 0.7.2"
        required: true
      frontend_version:
        description: "Frontend version to deploy (defaults to infra_version)"
        required: false
        default: ""

permissions:
  id-token: write
  contents: write

jobs:
  get_build:
    uses: ./.github/workflows/build_get.yml
    with:
      environment: ci
      lambda_version: ${{ inputs.infra_version }}
      frontend_version: ${{ inputs.frontend_version }}

  deploy:
    uses: ./.github/workflows/deploy.yml
    needs:
      - get_build
    with:
      environment: prod
      lambda_version: ${{ needs.get_build.outputs.lambda_version }}
      code_bucket: ${{ needs.get_build.outputs.code_bucket }}
      matrix: ${{ needs.get_build.outputs.lambda_version_files }}
      # we can also define a code-only deployment here if needed, as below
      # matrix: '["api"]'
