name: Prod Infra

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  get_build:
    name: Resolve
    uses: ./.github/workflows/build_get.yml
    with:
      environment: ci
      lambda_version: 0.9.4
      frontend_version: 0.9.4
      ecs_version: 0.9.4

  infra:
    name: Apply
    needs:
      - get_build
    uses: ./.github/workflows/infra.yml
    with:
      environment: prod
      infra_version: 0.9.4
      code_bucket: ${{ needs.get_build.outputs.code_bucket }}
      lambda_matrix: ${{ needs.get_build.outputs.lambda_version_files }}
      bootstrap_image_uri: ${{ needs.get_build.outputs.bootstrap_image_uri }}
      service_matrix: ${{ needs.get_build.outputs.ecs_service_matrix }}
