name: Kill Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        type: choice
        options:
          - dev
          - prod

concurrency: # only run destroy when no other deploy/destroy is running for the same environment
  group: deploy-${{ inputs.environment }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: write

env:
  TF_VAR_lambda_version: this
  AWS_OIDC_ROLE_ARN: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/aws-serverless-github-deploy-${{ inputs.environment }}-github-oidc-role

jobs:
  setup:
    name: Discover Directories
    uses: ./.github/workflows/get_directories.yml

  lambdas:
    name: Destroy Lambda Infra
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        value: ${{ fromJson(needs.setup.outputs.lambda_dirs) }}
    steps:
      - uses: actions/checkout@v6

      - name: Deploy ${{ matrix.value }} infra
        uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.1
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/${{ matrix.value }}
          tg_action: destroy

  frontend:
    name: Destroy Frontend Infra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Destroy frontend infra
        uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.1
        env:
          TF_VAR_api_invoke_url: "https://placeholder.execute-api.us-east-1.amazonaws.com"
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/frontend
          tg_action: destroy

  services:
    name: Destroy Service Infra
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        value: ${{ fromJson(needs.setup.outputs.ecs_service_dirs) }}
    steps:
      - uses: actions/checkout@v6

      - name: Destroy ${{ matrix.value }} infra
        uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.1
        env:
          TF_VAR_bootstrap: "true"
          TF_VAR_bootstrap_image_uri: "destroy-placeholder"
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/${{ matrix.value }}
          tg_action: destroy

  tasks:
    name: Destroy Task Infra
    runs-on: ubuntu-latest
    needs:
      - setup
      - services
    strategy:
      fail-fast: false
      matrix:
        value: ${{ fromJson(needs.setup.outputs.task_dirs) }}
    steps:
      - uses: actions/checkout@v6

      - name: Destroy ${{ matrix.value }} infra
        uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.1
        env:
          TF_VAR_image_uri: "destroy-placeholder"
          TF_VAR_debug_image_uri: "destroy-placeholder"
          TF_VAR_aws_otel_collector_image_uri: "destroy-placeholder"
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/${{ matrix.value }}
          tg_action: destroy

  network:
    name: Destroy Network Infra
    needs:
      - frontend
      - services
      - tasks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Destroy network infra
        uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.1
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/network
          tg_action: destroy

  security:
    name: Destroy Security Infra
    needs:
      - network
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Destroy security infra
        uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.1
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/security
          tg_action: destroy

  build-bucket:
    name: Destroy Code Bucket
    if: inputs.environment != 'prod'
    needs:
      - lambdas
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Destroy code
        uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.1
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/code_bucket
          tg_action: destroy

  ecr:
    name: Destroy ECR
    if: inputs.environment != 'prod'
    needs:
      - network
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Destroy code
        uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.1
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/ecr
          tg_action: destroy

  cluster:
    name: Destroy Cluster Infra
    needs:
      - network
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Destroy cluster infra
        uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.1
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/cluster
          tg_action: destroy
