name: Kill Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        type: choice
        options:
          - dev
          - prod

concurrency: # only run destroy when no other deploy/destroy is running for the same environment
  group: deploy-${{ inputs.environment }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: write

env:
  TF_VAR_lambda_version: this
  AWS_OIDC_ROLE_ARN: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/aws-serverless-github-deploy-${{ inputs.environment }}-github-oidc-role

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      lambda_dirs: ${{ steps.lambda_dirs.outputs.just_outputs }}
      service_dirs: ${{ steps.service_dirs.outputs.just_outputs }}
    steps:
      - uses: actions/checkout@v6

      - uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.1
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/oidc

      - name: Get Lambda Directories
        id: lambda_dirs
        uses: chrispsheehan/just-aws-oidc-action@0.3.0
        with:
          just_action: lambda-get-directories

      - name: Get Service Directories
        id: service_dirs
        uses: chrispsheehan/just-aws-oidc-action@0.3.0
        with:
          just_action: service-get-directories

  lambdas:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        value: ${{ fromJson(needs.setup.outputs.lambda_dirs) }}
    steps:
      - uses: actions/checkout@v6

      - name: Deploy ${{ matrix.value }} infra
        uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.1
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/${{ matrix.value }}
          tg_action: destroy

  frontend:
    needs: lambdas
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Destroy frontend infra
        uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.1
        env:
          TF_VAR_api_invoke_url: "https://placeholder.execute-api.us-east-1.amazonaws.com"
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/frontend
          tg_action: destroy

  cluster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Destroy cluster infra
        uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.1
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/cluster
          tg_action: destroy

  network:
    needs:
      - frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Destroy network infra
        uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.1
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/network
          tg_action: destroy

  security:
    needs:
      - network
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Destroy security infra
        uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.1
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/security
          tg_action: destroy

  build-bucket:
    if: inputs.environment != 'prod'
    needs:
      - lambdas
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Destroy code
        uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.1
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/code_bucket
          tg_action: destroy

  ecr:
    if: inputs.environment != 'prod'
    needs:
      - cluster
      - security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Destroy code
        uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.1
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/ecr
          tg_action: destroy
