name: Dev Infra Apply (no plan)

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  actions: read

jobs:
  infra:
    name: Apply
    uses: ./.github/workflows/shared_infra_apply.yml
    with:
      environment: dev
      infra_version: ${{ github.sha }}
      code_bucket: ""
      lambda_matrix: "[]"
      bootstrap_image_uri: ""
      service_matrix: "[]"
