name: Dev Infra Plan

on:
  workflow_dispatch:
  push:
    branches:
      - plan-artefacts

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  setup:
    name: Discover
    uses: ./.github/workflows/shared_directories_get.yml

  code:
    name: Artifacts
    uses: ./.github/workflows/shared_infra_releases.yml
    with:
      environment: dev
      infra_version: ${{ github.sha }}

  infra:
    name: Plan
    needs:
      - setup
      - code
    uses: ./.github/workflows/shared_infra_plan.yml
    with:
      environment: dev
      infra_version: ${{ github.sha }}
      code_bucket: ${{ needs.code.outputs.code_bucket }}
      lambda_matrix: ${{ needs.setup.outputs.lambda_dirs }}
      bootstrap_image_uri: ${{ needs.code.outputs.bootstrap_image_uri }}
      service_matrix: ${{ needs.setup.outputs.ecs_service_dirs }}
