name: Dev Infra Plan And Apply

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  actions: read

jobs:
  setup:
    name: Discover
    uses: ./.github/workflows/shared_directories_get.yml

  code:
    name: Artifacts
    uses: ./.github/workflows/shared_infra_releases.yml
    with:
      environment: dev
      infra_version: ${{ github.sha }}

  plan:
    name: Plan
    needs:
      - setup
      - code
    uses: ./.github/workflows/shared_infra_plan.yml
    with:
      environment: dev
      infra_version: ${{ github.sha }}
      code_bucket: ${{ needs.code.outputs.code_bucket }}
      lambda_matrix: ${{ needs.setup.outputs.lambda_dirs }}
      bootstrap_image_uri: ${{ needs.code.outputs.bootstrap_image_uri }}
      service_matrix: ${{ needs.setup.outputs.ecs_service_dirs }}

  apply:
    name: Apply Planned Infra
    needs:
      - plan
    uses: ./.github/workflows/shared_infra_apply_from_plan.yml
    with:
      environment: dev
      plan_artifact_run_id: ${{ github.run_id }}
