name: Dev Code Deploy
# This deploys code changes to dev without touching infra.

on:
  workflow_dispatch:
  push:
    branches:
      - s3-plan-artifacts

permissions:
  id-token: write
  contents: write

jobs:
  setup:
    name: Discover
    uses: ./.github/workflows/shared_directories_get.yml

  build:
    name: Build
    uses: ./.github/workflows/shared_build.yml
    needs:
      - setup
    with:
      environment: dev
      lambda_version: ${{ github.sha }}
      frontend_version: ${{ github.sha }}
      ecs_version: ${{ github.sha }}
      lambda_matrix: ${{ needs.setup.outputs.lambda_dirs }}
      ecs_matrix: ${{ needs.setup.outputs.container_dirs }}


  get_build:
    name: Resolve
    needs: build
    uses: ./.github/workflows/shared_build_get.yml
    with:
      environment: dev
      lambda_version: ${{ needs.build.outputs.lambda_version }}
      frontend_version: ${{ needs.build.outputs.frontend_version }}
      ecs_version: ${{ needs.build.outputs.ecs_version }}

  deploy:
    name: Deploy
    uses: ./.github/workflows/shared_deploy.yml
    needs:
      - setup
      - build
      - get_build
    with:
      environment: dev
      lambda_version: ${{ needs.build.outputs.lambda_version }}
      frontend_version: ${{ needs.build.outputs.frontend_version }}
      code_bucket: ${{ needs.get_build.outputs.code_bucket }}
      lambda_matrix: ${{ needs.setup.outputs.lambda_dirs }}
      task_matrix: ${{ needs.get_build.outputs.ecs_task_matrix }}
      ecs_image_uris: ${{ needs.get_build.outputs.ecs_image_uris }}
