on:
  workflow_call:
    inputs:
      environment:
        description: environment reference i.e. 'prod' or 'dev'
        required: true
        type: string
      infra_version:
        description: "Version of infrastructure (terraform) to be deployed"
        required: true
        type: string
      code_bucket:
        description: "Bucket containing build artifacts"
        required: true
        type: string
      bootstrap_image_uri:
        description: "Bootstrap ECS image URI"
        required: false
        type: string
        default: ""
      lambda_matrix:
        required: false
        type: string
        default: "[]"
      service_matrix:
        required: false
        type: string
        default: "[]"


concurrency: # only run one instance of workflow at any one time
  group: infra-${{ inputs.environment }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: write

env:
  AWS_OIDC_ROLE_ARN: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/aws-serverless-github-deploy-${{ inputs.environment }}-github-oidc-role

jobs:
  oidc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.infra_version }}

      - name: Deploy oidc role infra
        uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.1
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/oidc

  frontend:
    needs: lambdas
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.infra_version }}

      - name: Get api infra
        uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.1
        id: get-api
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/api
          tg_action: init

      - name: Get api invoke url
        id: get_api_vars
        env:
          TG_OUTPUTS: ${{ steps.get-api.outputs.tg_outputs }}
        run: |
          echo "invoke_url=$(echo $TG_OUTPUTS | jq -r '.invoke_url.value')" >> $GITHUB_OUTPUT

      - name: Deploy frontend infra
        uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.1
        env:
          TF_VAR_api_invoke_url: ${{ steps.get_api_vars.outputs.invoke_url }}
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/frontend

  cluster:
    needs: oidc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.infra_version }}

      - name: Deploy cluster infra
        uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.1
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/cluster

  lambdas:
    needs: oidc
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # this is to prevent terraform lock issues
      matrix:
        value: ${{ fromJson(inputs.lambda_matrix) }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.infra_version }}

      - name: Deploy ${{ matrix.value }} infra
        uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.1
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/${{ matrix.value }}

  services:
    needs:
      - cluster
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        value: ${{ fromJson(inputs.service_matrix) }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.infra_version }}

      - name: Deploy ${{ matrix.value }} bootstrap service infra
        uses: chrispsheehan/terragrunt-aws-oidc-action@0.4.1
        env:
          TF_VAR_bootstrap: "true"
          TF_VAR_bootstrap_image_uri: ${{ inputs.bootstrap_image_uri }}
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/${{ matrix.value }}
