name: Shared Infra Apply

on:
  workflow_call:
    inputs:
      environment:
        description: environment reference i.e. 'prod' or 'dev'
        required: true
        type: string
      infra_version:
        description: "Version of infrastructure (terraform) to be applied"
        required: true
        type: string
      bootstrap_image_uri:
        description: "Bootstrap ECS image URI"
        required: false
        type: string
        default: ""

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  infra:
    uses: ./.github/workflows/shared_infra.yml
    with:
      environment: ${{ inputs.environment }}
      infra_version: ${{ inputs.infra_version }}
      bootstrap_image_uri: ${{ inputs.bootstrap_image_uri }}
      tg_action: apply
