name: Shared Infra Releases

on:
  workflow_call:
    inputs:
      environment:
        description: environment reference i.e. 'prod' or 'dev'
        required: true
        type: string
      infra_version:
        description: "Version of infrastructure (terraform) to be deployed"
        required: true
        type: string
    outputs:
      code_bucket:
        description: "Bucket containing build artifacts"
        value: ${{ jobs.bucket.outputs.bucket_name }}
      repository_url:
        description: "ECR repository url"
        value: ${{ jobs.ecr.outputs.repository_url }}
      bootstrap_image_uri:
        description: "Bootstrap ECS image URI"
        value: ${{ jobs.ecr.outputs.bootstrap_image_uri }}

concurrency: # only run one instance of workflow at any one time
  group: ${{ github.workflow }}-${{ inputs.environment }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: write

env:
  AWS_OIDC_ROLE_ARN: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.PROJECT_NAME }}-${{ inputs.environment }}-github-oidc-role

jobs:
  ecr:
    runs-on: ubuntu-latest
    outputs:
      repository_url: ${{ steps.get_repository_url.outputs.repository_url }}
      bootstrap_image_uri: ${{ steps.set_bootstrap_image_uri.outputs.bootstrap_image_uri }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.infra_version }}

      - name: Deploy ECR
        id: deploy_ecr
        uses: ./.github/actions/terragrunt
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/ecr

      - name: Get ECR repository url
        id: get_repository_url
        env:
          TG_OUTPUTS: ${{ steps.deploy_ecr.outputs.tg_outputs }}
        run: |
          echo "repository_url=$(echo "$TG_OUTPUTS" | jq -r '.repository_url.value')" >> "$GITHUB_OUTPUT"

      - name: Build and push bootstrap image
        uses: ./.github/actions/just
        env:
          SOURCE_IMAGE: nginx:latest
          IMAGE_URI: ${{ steps.get_repository_url.outputs.repository_url }}:bootstrap-${{ inputs.infra_version }}
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          justfile_path: justfile.deploy
          just_action: docker-mirror docker-push

      - name: Set bootstrap image uri
        id: set_bootstrap_image_uri
        env:
          BOOTSTRAP_IMAGE_URI: ${{ steps.get_repository_url.outputs.repository_url }}:bootstrap-${{ inputs.infra_version }}
        run: |
          echo "bootstrap_image_uri=$BOOTSTRAP_IMAGE_URI" >> "$GITHUB_OUTPUT"

  bucket:
    runs-on: ubuntu-latest
    outputs:
      bucket_name: ${{ steps.get_bucket_name.outputs.bucket }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.infra_version }}

      - name: Read Lambda artifact dir
        id: lambda_artifact_dir
        uses: ./.github/actions/just
        with:
          justfile_path: justfile.ci
          just_action: code-bucket-get-lambda-artifact-dir

      - name: Read frontend artifact dir
        id: frontend_artifact_dir
        uses: ./.github/actions/just
        with:
          justfile_path: justfile.ci
          just_action: code-bucket-get-frontend-artifact-dir

      - name: Read AppSpec artifact dir
        id: appspec_artifact_dir
        uses: ./.github/actions/just
        with:
          justfile_path: justfile.ci
          just_action: code-bucket-get-appspec-artifact-dir

      - name: Read infra plan dir
        id: infra_plan_dir
        uses: ./.github/actions/just
        with:
          justfile_path: justfile.ci
          just_action: code-bucket-get-infra-plan-dir

      - name: Deploy build artifact bucket
        id: deploy_bucket
        uses: ./.github/actions/terragrunt
        env:
          TF_VAR_lambda_artifact_dir: ${{ steps.lambda_artifact_dir.outputs.just_outputs }}
          TF_VAR_frontend_artifact_dir: ${{ steps.frontend_artifact_dir.outputs.just_outputs }}
          TF_VAR_appspec_artifact_dir: ${{ steps.appspec_artifact_dir.outputs.just_outputs }}
          TF_VAR_infra_plan_dir: ${{ steps.infra_plan_dir.outputs.just_outputs }}
        with:
          aws_oidc_role_arn: ${{ env.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{ inputs.environment }}/aws/code_bucket

      - name: Get bucket name
        id: get_bucket_name
        env:
          TG_OUTPUTS: ${{ steps.deploy_bucket.outputs.tg_outputs  }}
        run: |
          echo "bucket=$(echo $TG_OUTPUTS | jq -r '.bucket.value')" >> $GITHUB_OUTPUT
